mod add;
mod bindgen;
mod build;
mod check;
mod completions;
mod doc;
mod format;
pub mod help;
mod learn;
mod lsp;
mod new;
mod project;
pub(crate) mod reconciliation;
mod run;
mod script;
mod script_add;
mod script_deps;
mod script_edit;
mod script_sync;
mod script_table;
mod sync;
mod test;
mod upgrade;

#[cfg(test)]
pub(crate) use script::script_build_dir;
pub(crate) use script::script_locator;
pub(crate) use script_deps::Mode as ScriptResolveMode;

pub use add::add;
pub use bindgen::bindgen;
pub use build::{build, emit};
pub use check::check;
pub use completions::completions;
pub use doc::{doc, doc_search};
pub use format::format;
pub use learn::learn;
pub use lsp::lsp;
pub use new::new_project;
pub use run::run;
pub use sync::sync;
pub use test::test;
pub use upgrade::upgrade;
