package emit

import (
	"fmt"
	"slices"
	"strconv"
	"strings"

	"github.com/ivov/lisette/bindgen/internal/config"
	"github.com/ivov/lisette/bindgen/internal/convert"
	"github.com/ivov/lisette/bindgen/internal/extract"
)

func writeSkippedFieldComment(w *strings.Builder, indent string, f convert.StructField) {
	fmt.Fprintf(w, "%s// SKIPPED field %q: %s — %s\n", indent, f.Name, f.SkipReason.Code, f.SkipReason.Message)
}

func escapeSealId(id string) string {
	id = strings.ReplaceAll(id, `\`, `\\`)
	id = strings.ReplaceAll(id, `"`, `\"`)
	return id
}

func writeSkipNote(w *strings.Builder, indent, label string, reason *convert.SkipReason) {
	fmt.Fprintf(w, "%s// SKIPPED %s: %s\n", indent, label, reason.Code)
	fmt.Fprintf(w, "%s// %s\n", indent, reason.Message)
}

type stats struct {
	functions int
	methods   int
	types     int
	constants int
	variables int
}

type Emitter struct {
	buf               strings.Builder
	stats             stats
	skipped           int
	methods           map[string][]convert.ConvertResult // receiver type name -> methods
	cfg               config.Config
	pkgPath           string
	pkgName           string            // package name, used to self-qualify prelude-colliding types
	pkgAliases        map[string]string // package path -> local prefix used in references
	bitFlagSetTypes   map[string]bool   // type names emitted as #[go(bit_flag_set)] newtypes
	closedDomainTypes map[string]bool   // type names emitted as #[go(closed_domain)] newtypes
}

func NewEmitter(cfg *config.Config, pkgPath, pkgName string, bitFlagSetTypes, closedDomainTypes map[string]bool) *Emitter {
	var effectiveConfig config.Config
	if cfg != nil {
		effectiveConfig = *cfg
	}
	return &Emitter{
		methods:           make(map[string][]convert.ConvertResult),
		cfg:               effectiveConfig,
		pkgPath:           pkgPath,
		pkgName:           pkgName,
		bitFlagSetTypes:   bitFlagSetTypes,
		closedDomainTypes: closedDomainTypes,
	}
}

func (e *Emitter) EmitHeader(pkg, pkgName, lisetteVersion, goToolchainVersion string) {
	e.buf.WriteString("// Generated by Lisette bindgen\n")
	fmt.Fprintf(&e.buf, "// Source: %s (%s)\n", pkg, packageSourceType(pkg))
	// Lisette derives a Go import's local name from the segment before a `/vN`
	// suffix, so a package actually named `vN` must declare `// Package:` itself.
	if lastSegment := pkg[strings.LastIndex(pkg, "/")+1:]; pkgName != lastSegment || hasMajorVersionSuffix(pkg) {
		fmt.Fprintf(&e.buf, "// Package: %s\n", pkgName)
	}
	fmt.Fprintf(&e.buf, "// Go: %s\n", strings.TrimPrefix(goToolchainVersion, "go"))
	fmt.Fprintf(&e.buf, "// Lisette: %s\n", lisetteVersion)
	e.buf.WriteString("\n")
}

// hasMajorVersionSuffix reports whether the path ends in a `/v2`+ major-version suffix.
func hasMajorVersionSuffix(pkgPath string) bool {
	last := pkgPath[strings.LastIndex(pkgPath, "/")+1:]
	if len(last) < 2 || last[0] != 'v' {
		return false
	}
	major, err := strconv.Atoi(last[1:])
	return err == nil && major >= 2
}

func packageSourceType(pkg string) string {
	if strings.HasPrefix(pkg, "/") || strings.HasPrefix(pkg, "./") || strings.HasPrefix(pkg, "../") {
		return "local"
	}

	if strings.HasPrefix(pkg, "golang.org/x/") {
		return "Go extended"
	}

	firstSegment := pkg
	if idx := strings.Index(pkg, "/"); idx != -1 {
		firstSegment = pkg[:idx]
	}

	if strings.Contains(firstSegment, ".") {
		return "Go community"
	}

	return "Go stdlib"
}

// EmitImports renders the import block. reserveSelfName is set when the package
// declares a prelude-colliding type, so a same-named import cannot claim the
// bare prefix that the self-qualified references rely on.
func (e *Emitter) EmitImports(externalPkgs convert.ExternalPkgs, reserveSelfName bool) {
	if len(externalPkgs) == 0 {
		return
	}

	selfName := ""
	if reserveSelfName {
		selfName = e.pkgName
	}
	e.pkgAliases = computePkgAliases(externalPkgs, selfName)

	paths := make([]string, 0, len(externalPkgs))
	for path := range externalPkgs {
		paths = append(paths, path)
	}
	slices.Sort(paths)

	for _, path := range paths {
		prefix := e.pkgAliases[path]
		if prefix == externalPkgs[path] {
			fmt.Fprintf(&e.buf, "import \"go:%s\"\n", path)
		} else {
			fmt.Fprintf(&e.buf, "import %s \"go:%s\"\n", prefix, path)
		}
	}

	e.buf.WriteString("\n")
}

// computePkgAliases resolves each path to a local prefix. On a Go-declared
// name collision (e.g. `html/template` vs `text/template`) the path with
// the fewest segments keeps the bare name (lex tiebreaker); the rest get a
// synthesized alias by widening the trailing-segment window until unique
// against bare names and previously-synthesized aliases. selfName is reserved
// so an import sharing the current package's name cannot claim the bare prefix,
// which self-qualified references (`pkg.Type`) rely on.
func computePkgAliases(externalPkgs convert.ExternalPkgs, selfName string) map[string]string {
	byName := make(map[string][]string)
	for path, name := range externalPkgs {
		byName[name] = append(byName[name], path)
	}

	aliases := make(map[string]string, len(externalPkgs))
	taken := make(map[string]bool)
	if selfName != "" {
		taken[selfName] = true
	}
	pending := make([]string, 0, len(externalPkgs)-len(byName))

	for name, paths := range byName {
		slices.SortFunc(paths, compareByDepth)
		if taken[name] {
			pending = append(pending, paths...)
			continue
		}
		aliases[paths[0]] = name
		taken[name] = true
		pending = append(pending, paths[1:]...)
	}

	slices.SortFunc(pending, compareByDepth)
	for _, path := range pending {
		alias := aliasForPath(path, taken)
		aliases[path] = alias
		taken[alias] = true
	}

	return aliases
}

func compareByDepth(a, b string) int {
	if as, bs := strings.Count(a, "/"), strings.Count(b, "/"); as != bs {
		return as - bs
	}
	return strings.Compare(a, b)
}

func aliasForPath(path string, taken map[string]bool) string {
	parts := strings.Split(path, "/")
	for n := 2; n <= len(parts); n++ {
		candidate := joinAndSanitize(parts[len(parts)-n:])
		if !taken[candidate] {
			return candidate
		}
	}
	base := joinAndSanitize(parts)
	if !taken[base] {
		return base
	}
	for i := 2; ; i++ {
		candidate := fmt.Sprintf("%s_%d", base, i)
		if !taken[candidate] {
			return candidate
		}
	}
}

func joinAndSanitize(parts []string) string {
	var b strings.Builder
	for i, p := range parts {
		if i > 0 {
			b.WriteByte('_')
		}
		b.WriteString(sanitizeIdent(p))
	}
	return b.String()
}

func sanitizeIdent(s string) string {
	var b strings.Builder
	b.Grow(len(s))
	for _, r := range s {
		switch {
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z', r >= '0' && r <= '9', r == '_':
			b.WriteRune(r)
		default:
			b.WriteRune('_')
		}
	}
	return b.String()
}

func (e *Emitter) EmitExport(result convert.ConvertResult) {
	switch result.Kind {
	case extract.ExportFunction:
		e.emitFunction(result)
		e.stats.functions++
	case extract.ExportMethod:
		if e.collectMethod(result) {
			e.stats.methods++
		}
	case extract.ExportType:
		e.emitType(result)
		e.stats.types++
	case extract.ExportConstant:
		e.emitConst(result)
		e.stats.constants++
	case extract.ExportVariable:
		e.emitVariable(result)
		e.stats.variables++
	}
}

func (e *Emitter) collectMethod(result convert.ConvertResult) bool {
	if result.Receiver == nil {
		return false
	}

	baseTypeName := result.Receiver.BaseTypeName
	if baseTypeName == "" {
		return false
	}

	e.methods[baseTypeName] = append(e.methods[baseTypeName], result)
	return true
}

// CollectSkippedMethod buckets a skipped method under its receiver type so
// the impl block renders a `// SKIPPED method` comment in place of the
// unrepresentable signature. Returns false when the receiver could not be
// established (in which case the caller falls back to a top-level skip).
func (e *Emitter) CollectSkippedMethod(result convert.ConvertResult) bool {
	if result.Receiver == nil || result.Receiver.BaseTypeName == "" {
		return false
	}
	e.methods[result.Receiver.BaseTypeName] = append(e.methods[result.Receiver.BaseTypeName], result)
	e.skipped++
	return true
}

func (e *Emitter) EmitUnloadableNote(firstError string) {
	e.buf.WriteString("// Status: UNLOADABLE — package could not be type-checked on this host\n")
	fmt.Fprintf(&e.buf, "// First error: %s\n", firstError)
	e.buf.WriteString("\n")
}

func (e *Emitter) EmitSkipped(result convert.ConvertResult) {
	fmt.Fprintf(&e.buf, "// SKIPPED: %s - %s\n", result.Name, result.SkipReason.Code)
	fmt.Fprintf(&e.buf, "// %s\n", result.SkipReason.Message)

	if result.SkipReason.EmitOpaqueType {
		fmt.Fprintf(&e.buf, "pub type %s%s\n", result.Name, result.TypeParams.DeclBlock())
		e.stats.types++
	}

	e.buf.WriteString("\n")
	e.skipped++
}

func (e *Emitter) EmitImplBlocks() {
	if len(e.methods) == 0 {
		return
	}

	typeNames := make([]string, 0, len(e.methods))
	for typeName := range e.methods {
		typeNames = append(typeNames, typeName)
	}
	slices.Sort(typeNames)

	for _, typeName := range typeNames {
		methods := e.methods[typeName]
		if len(methods) == 0 {
			continue
		}

		var typeParams convert.TypeParamSpecs
		if methods[0].Receiver != nil {
			typeParams = methods[0].Receiver.TypeParams
		}

		implName := convert.SelfQualify(e.pkgName, typeName, len(typeParams))
		if len(typeParams) > 0 {
			fmt.Fprintf(&e.buf, "impl<%s> %s<%s> {\n", typeParams.FormatDecl(), implName, typeParams.FormatUse())
		} else {
			fmt.Fprintf(&e.buf, "impl %s {\n", implName)
		}
		for _, method := range methods {
			e.emitMethodInImpl(method, implName)
		}

		e.buf.WriteString("}\n\n")
	}
}

func (e *Emitter) Summary() string {
	var buf strings.Builder
	total := e.stats.functions + e.stats.methods + e.stats.types + e.stats.constants + e.stats.variables
	fmt.Fprintf(&buf, "Generated: %d functions, %d methods, %d types, %d constants, %d variables\n",
		e.stats.functions, e.stats.methods, e.stats.types, e.stats.constants, e.stats.variables)
	fmt.Fprintf(&buf, "Total: %d symbols\n", total)
	if e.skipped > 0 {
		fmt.Fprintf(&buf, "Skipped: %d symbols\n", e.skipped)
	}
	return buf.String()
}

func (e *Emitter) String() string {
	raw := e.buf.String()
	if len(e.pkgAliases) > 0 {
		pairs := make([]string, 0, len(e.pkgAliases)*2)
		for path, prefix := range e.pkgAliases {
			pairs = append(pairs, convert.PkgRefStart+path+convert.PkgRefEnd, prefix)
		}
		raw = strings.NewReplacer(pairs...).Replace(raw)
	}
	return strings.TrimRight(raw, "\n") + "\n"
}

func formatParams(params []convert.FunctionParameter) []string {
	out := make([]string, 0, len(params))
	for _, p := range params {
		out = append(out, fmt.Sprintf("%s: %s", p.Name, p.Type))
	}
	return out
}

// formatSignature builds a signature line; keyword carries any indent and trailing space (e.g. "  fn ").
func formatSignature(keyword, name, declBlock string, params []string, hasReturn bool, returnType string) string {
	var b strings.Builder
	b.WriteString(keyword)
	b.WriteString(name)
	b.WriteString(declBlock)
	b.WriteString("(")
	b.WriteString(strings.Join(params, ", "))
	b.WriteString(")")
	if hasReturn {
		b.WriteString(" -> ")
		b.WriteString(returnType)
	}
	return b.String()
}

func (e *Emitter) emitFunction(result convert.ConvertResult) {
	if result.SkipNote != nil {
		writeSkipNote(&e.buf, "", "returns-with", result.SkipNote)
	}
	e.emitDocWithIndent(result.Doc, "")

	if result.CommaOk {
		e.buf.WriteString("#[go(comma_ok)]\n")
	}
	if result.CollapsedTypeParamRecipe != "" {
		fmt.Fprintf(&e.buf, "#[go(collapsed_type_params, %q)]\n", result.CollapsedTypeParamRecipe)
	}
	if result.SentinelInt != nil {
		e.buf.WriteString(sentinelFlag(*result.SentinelInt) + "\n")
	}
	if result.SupersededBy != "" {
		fmt.Fprintf(&e.buf, "#[go(superseded_by, %q)]\n", result.SupersededBy)
	}
	if e.shouldAllowUnusedResult(result.Name, "", result) {
		fmt.Fprintf(&e.buf, "#[allow(%s)]\n", allowDiscardLint(result.ReturnType))
	}
	if result.HasReturn() && e.cfg.ShouldAllowUnusedValue(e.pkgPath, result.Name) {
		e.buf.WriteString("#[allow(unused_value)]\n")
	}

	e.buf.WriteString(formatSignature("pub fn ", result.Name, result.TypeParams.DeclBlock(),
		formatParams(result.Params), result.HasReturn(), result.ReturnType))
	e.buf.WriteString("\n\n")
}

func allowDiscardLint(returnType string) string {
	if strings.HasPrefix(returnType, "Partial<") {
		return "unused_partial"
	}
	return "unused_result"
}

// shouldAllowUnusedResult reports whether a function or method should carry a
// discard-suppression attribute, taking config over the signature heuristic.
func (e *Emitter) shouldAllowUnusedResult(qualifiedName, methodName string, result convert.ConvertResult) bool {
	if e.cfg.ShouldAllowUnusedResult(e.pkgPath, qualifiedName) {
		return true
	}

	name := methodName
	if name == "" {
		name = result.Name
	}

	return isConventionalDiscard(name, len(result.Params), result.ReturnType)
}

// shouldAllowUnusedResultOnMethod is the same for an interface method, which
// has no receiver to qualify itself with.
func (e *Emitter) shouldAllowUnusedResultOnMethod(interfaceName string, m convert.InterfaceMethod) bool {
	if e.cfg.ShouldAllowUnusedResult(e.pkgPath, interfaceName+"."+m.Name) {
		return true
	}

	return isConventionalDiscard(m.Name, len(m.Params), m.ReturnType)
}

// isConventionalDiscard reports whether Go leaves this cleanup method's error
// unchecked by convention.
func isConventionalDiscard(name string, paramCount int, returnType string) bool {
	switch name {
	case "Close", "Flush":
		return paramCount == 0 && returnType == "Result<(), error>"
	}

	return false
}

func (e *Emitter) emitMethodInImpl(result convert.ConvertResult, recvName string) {
	if result.SkipReason != nil {
		fmt.Fprintf(&e.buf, "  // SKIPPED method %q: %s — %s\n", result.Name, result.SkipReason.Code, result.SkipReason.Message)
		return
	}

	if result.SkipNote != nil {
		writeSkipNote(&e.buf, "  ", "returns-with", result.SkipNote)
	}
	e.emitDocWithIndent(result.Doc, "  ")

	if result.CommaOk {
		e.buf.WriteString("  #[go(comma_ok)]\n")
	}
	if result.Receiver != nil && result.Receiver.Mutable && !result.Receiver.IsPointer {
		e.buf.WriteString("  #[go(value_method_set)]\n")
	}
	if result.SentinelInt != nil {
		e.buf.WriteString("  " + sentinelFlag(*result.SentinelInt) + "\n")
	}
	if result.SupersededBy != "" {
		fmt.Fprintf(&e.buf, "  #[go(superseded_by, %q)]\n", result.SupersededBy)
	}
	if result.Receiver != nil {
		qualifiedName := result.Receiver.BaseTypeName + "." + result.Name
		if e.shouldAllowUnusedResult(qualifiedName, result.Name, result) {
			fmt.Fprintf(&e.buf, "  #[allow(%s)]\n", allowDiscardLint(result.ReturnType))
		}
	}
	allowUnusedValue := result.BuilderMethod
	if !allowUnusedValue && result.Receiver != nil && result.HasReturn() {
		qualifiedName := result.Receiver.BaseTypeName + "." + result.Name
		allowUnusedValue = e.cfg.ShouldAllowUnusedValue(e.pkgPath, qualifiedName)
	}
	if allowUnusedValue {
		e.buf.WriteString("  #[allow(unused_value)]\n")
	}
	if result.SealId != "" {
		fmt.Fprintf(&e.buf, "  #[go(unexported, \"%s\")]\n", escapeSealId(result.SealId))
	}

	var params []string
	if result.Receiver != nil && (result.Receiver.IsPointer || result.Receiver.Mutable) {
		typeName := recvName + result.Receiver.TypeParams.UseBlock()
		// A Go pointer receiver may write unless the analysis proved
		// otherwise, so the worst case keeps the `mut` qualifier.
		if result.Receiver.ProvenReadOnly && !result.Receiver.Mutable {
			params = append(params, fmt.Sprintf("self: Ref<%s>", typeName))
		} else {
			params = append(params, fmt.Sprintf("self: mut Ref<%s>", typeName))
		}
	} else {
		params = append(params, "self")
	}
	params = append(params, formatParams(result.Params)...)

	e.buf.WriteString(formatSignature("  fn ", result.Name, result.TypeParams.DeclBlock(),
		params, result.HasReturn(), result.ReturnType))
	e.buf.WriteString("\n")
}

func (e *Emitter) emitType(result convert.ConvertResult) {
	e.emitDocWithIndent(result.Doc, "")

	switch {
	case result.IsInterface:
		e.emitInterface(result)
	case len(result.Fields) > 0:
		e.emitStruct(result)
	case result.LisetteType != "":
		e.emitNewtypeOrAlias(result)
	default:
		e.emitOpaqueType(result)
	}
}

func (e *Emitter) emitInterface(result convert.ConvertResult) {
	var signature strings.Builder
	signature.WriteString("pub interface ")
	signature.WriteString(result.Name)
	signature.WriteString(result.TypeParams.DeclBlock())

	if len(result.InterfaceMethods) == 0 {
		signature.WriteString(" {}")
	} else {
		signature.WriteString(" {\n")
		for _, m := range result.InterfaceMethods {
			if m.SealId != "" {
				fmt.Fprintf(&signature, "  #[go(unexported, \"%s\")]\n", escapeSealId(m.SealId))
			}
			if m.CommaOk {
				signature.WriteString("  #[go(comma_ok)]\n")
			}
			if m.BuilderMethod {
				signature.WriteString("  #[allow(unused_value)]\n")
			}
			if e.shouldAllowUnusedResultOnMethod(result.Name, m) {
				fmt.Fprintf(&signature, "  #[allow(%s)]\n", allowDiscardLint(m.ReturnType))
			}
			signature.WriteString(formatSignature("  fn ", m.Name, "",
				formatParams(m.Params), m.HasReturn(), m.ReturnType))
			signature.WriteString("\n")
		}
		signature.WriteString("}")
	}

	e.buf.WriteString(signature.String())
	e.buf.WriteString("\n\n")
}

func (e *Emitter) emitStruct(result convert.ConvertResult) {
	typeName := result.Name

	allSkipped := true
	for _, f := range result.Fields {
		if f.SkipReason == nil {
			allSkipped = false
			break
		}
	}

	if allSkipped {
		for _, f := range result.Fields {
			writeSkippedFieldComment(&e.buf, "", f)
		}
		if result.UnexportedType {
			e.buf.WriteString("#[go(unexported)]\n")
		}
		if result.HasHiddenEmbed {
			e.buf.WriteString("#[go(hidden_embed)]\n")
		}
		if result.ZeroSafe {
			e.buf.WriteString("#[go(zero_safe)]\n")
		}
		fmt.Fprintf(&e.buf, "pub type %s%s\n\n", typeName, result.TypeParams.DeclBlock())
		return
	}

	var sig strings.Builder
	if result.AnonStruct {
		sig.WriteString("#[go(anon_struct)]\n")
	}
	if result.UnexportedType {
		sig.WriteString("#[go(unexported)]\n")
	}
	if result.HasHiddenEmbed {
		sig.WriteString("#[go(hidden_embed)]\n")
	}
	if result.HasHiddenFields {
		sig.WriteString("#[go(hidden_fields)]\n")
	}
	if result.ZeroSafe {
		sig.WriteString("#[go(zero_safe)]\n")
	}
	if result.ZeroUnsafe {
		sig.WriteString("#[go(zero_unsafe)]\n")
	}
	sig.WriteString("pub struct ")
	sig.WriteString(typeName)
	sig.WriteString(result.TypeParams.DeclBlock())

	sig.WriteString(" {\n")
	for _, f := range result.Fields {
		if f.SkipReason != nil {
			writeSkippedFieldComment(&sig, "  ", f)
			continue
		}
		if f.Doc != "" {
			for line := range strings.SplitSeq(f.Doc, "\n") {
				sig.WriteString("  /// ")
				sig.WriteString(line)
				sig.WriteString("\n")
			}
		}
		if f.IsEmbedded {
			sig.WriteString("  embed ")
			sig.WriteString(f.Type)
			sig.WriteString(",\n")
			continue
		}
		sig.WriteString("  pub ")
		sig.WriteString(f.Name)
		sig.WriteString(": ")
		sig.WriteString(f.Type)
		sig.WriteString(",\n")
	}
	sig.WriteString("}")

	e.buf.WriteString(sig.String())
	e.buf.WriteString("\n\n")
}

func (e *Emitter) emitNewtypeOrAlias(result convert.ConvertResult) {
	typeName := result.Name
	var sig strings.Builder

	// Lisette rejects self-referential type aliases, so a Go function-type
	// like `type Filter func([]Filter)` falls back to an opaque type;
	// downstream signatures referencing it still resolve.
	isFnType := strings.HasPrefix(result.LisetteType, "fn(")
	isRecursiveFnAlias := isFnType && containsIdent(result.LisetteType, typeName)

	if isRecursiveFnAlias {
		sig.WriteString("pub type ")
		sig.WriteString(typeName)
		sig.WriteString(result.TypeParams.DeclBlock())
	} else if isFnType || result.IsTypeAlias {
		sig.WriteString("pub type ")
		sig.WriteString(typeName)
		sig.WriteString(result.TypeParams.DeclBlock())
		sig.WriteString(" = ")
		sig.WriteString(result.LisetteType)
	} else {
		if e.bitFlagSetTypes[typeName] {
			sig.WriteString("#[go(bit_flag_set)]\n")
		}
		if e.closedDomainTypes[typeName] {
			sig.WriteString("#[go(closed_domain)]\n")
		}
		sig.WriteString("pub struct ")
		sig.WriteString(typeName)
		sig.WriteString(result.TypeParams.DeclBlock())
		sig.WriteString("(")
		sig.WriteString(result.LisetteType)
		sig.WriteString(")")
	}

	e.buf.WriteString(sig.String())
	e.buf.WriteString("\n\n")
}

func (e *Emitter) emitOpaqueType(result convert.ConvertResult) {
	var signature strings.Builder
	if result.UnexportedType {
		signature.WriteString("#[go(unexported)]\n")
	}
	if result.HasHiddenEmbed {
		signature.WriteString("#[go(hidden_embed)]\n")
	}
	if result.ZeroSafe {
		signature.WriteString("#[go(zero_safe)]\n")
	}
	signature.WriteString("pub type ")
	signature.WriteString(result.Name)
	signature.WriteString(result.TypeParams.DeclBlock())

	e.buf.WriteString(signature.String())
	e.buf.WriteString("\n\n")
}

func (e *Emitter) emitConst(result convert.ConvertResult) {
	if result.SkipNote != nil {
		writeSkipNote(&e.buf, "", "type-with", result.SkipNote)
	}
	e.emitDocWithIndent(result.Doc, "")

	if result.ConstValue != "" {
		if e.isInferredNamedType(result.LisetteType) {
			fmt.Fprintf(&e.buf, "pub const %s: %s = %s\n\n", result.Name, result.LisetteType, result.ConstValue)
		} else {
			fmt.Fprintf(&e.buf, "pub const %s = %s\n\n", result.Name, result.ConstValue)
		}
	} else {
		fmt.Fprintf(&e.buf, "pub const %s: %s\n\n", result.Name, result.LisetteType)
	}
}

func (e *Emitter) isInferredNamedType(typeStr string) bool {
	basicTypes := map[string]bool{
		"bool":       true,
		"int":        true,
		"int8":       true,
		"int16":      true,
		"int32":      true,
		"int64":      true,
		"uint":       true,
		"uint8":      true,
		"uint16":     true,
		"uint32":     true,
		"uint64":     true,
		"uintptr":    true,
		"float32":    true,
		"float64":    true,
		"complex64":  true,
		"complex128": true,
		"string":     true,
		"byte":       true,
		"rune":       true,
		"error":      true,
		"Unknown":    true,
		"()":         true,
	}
	return !basicTypes[typeStr] && !strings.Contains(typeStr, "<")
}

func (e *Emitter) emitVariable(result convert.ConvertResult) {
	if result.SkipNote != nil {
		writeSkipNote(&e.buf, "", "type-with", result.SkipNote)
	}
	e.emitDocWithIndent(result.Doc, "")
	fmt.Fprintf(&e.buf, "pub var %s: %s\n\n", result.Name, result.LisetteType)
}

func (e *Emitter) EmitTypedConst(result convert.ConvertResult, typeName string) {
	e.emitDocWithIndent(result.Doc, "")
	fmt.Fprintf(&e.buf, "pub const %s: %s = %s\n\n", result.Name, typeName, result.ConstValue)
	e.stats.constants++
}

func (e *Emitter) emitDocWithIndent(doc, indent string) {
	if doc == "" {
		return
	}

	for line := range strings.SplitSeq(doc, "\n") {
		e.buf.WriteString(indent)
		e.buf.WriteString("/// ")
		e.buf.WriteString(line)
		e.buf.WriteString("\n")
	}
}

func sentinelFlag(value int) string {
	switch value {
	case -1:
		return "#[go(sentinel_minus_one)]"
	}
	panic(fmt.Sprintf("bindgen: unsupported sentinel value %d (add a flag mapping)", value))
}

// containsIdent reports whether name appears in s as a standalone identifier.
func containsIdent(s, name string) bool {
	if name == "" {
		return false
	}
	for i := 0; ; {
		rel := strings.Index(s[i:], name)
		if rel < 0 {
			return false
		}
		idx := i + rel
		end := idx + len(name)
		var before, after byte
		if idx > 0 {
			before = s[idx-1]
		}
		if end < len(s) {
			after = s[end]
		}
		if !isIdentByte(before) && !isIdentByte(after) {
			return true
		}
		i = idx + 1
	}
}

func isIdentByte(b byte) bool {
	return b == '_' ||
		(b >= 'a' && b <= 'z') ||
		(b >= 'A' && b <= 'Z') ||
		(b >= '0' && b <= '9')
}
