package cli

import (
	"fmt"
	"maps"
	"os"
	"path/filepath"
	"slices"
	"strings"
)

const rustIndexFileTemplate = `// Generated by Lisette bindgen. DO NOT EDIT.

pub(crate) const TYPEDEF_BUNDLE: &str = include_str!(concat!(env!("OUT_DIR"), "/go_typedefs.data"));

pub use crate::typedef_index::{
    get_go_stdlib_package_targets, get_go_stdlib_packages, get_go_stdlib_typedef,
};
`

func generateRustIndexFile(outDir string, partition partitioned, targets []Target) error {
	sourceDirectory := filepath.Join(outDir, "..", "src")
	if _, err := os.Stat(sourceDirectory); os.IsNotExist(err) {
		return nil
	}

	var metadata strings.Builder
	for _, packagePath := range slices.Sorted(maps.Keys(partition)) {
		partitionedPackage := partition[packagePath]
		if len(partitionedPackage.variants) == 1 {
			fmt.Fprintf(&metadata, "common\t%s\t%s.d.lis\n", packagePath, packagePath)
		} else {
			for _, target := range targets {
				for _, variant := range partitionedPackage.variants {
					if slices.Contains(variant.targets, target) {
						filename := filepath.ToSlash(suffixedPath(packagePath, variant.canonical))
						fmt.Fprintf(&metadata, "overlay\t%s\t%s\t%s\t%s\n", target.goos, target.goarch, packagePath, filename)
					}
				}
			}
		}
		if len(partitionedPackage.targets) < len(targets) {
			fmt.Fprintf(&metadata, "targets\t%s", packagePath)
			for _, target := range partitionedPackage.targets {
				fmt.Fprintf(&metadata, "\t%s\t%s", target.goos, target.goarch)
			}
			metadata.WriteByte('\n')
		}
	}

	if err := os.WriteFile(filepath.Join(sourceDirectory, "go_modules.tsv"), []byte(metadata.String()), 0644); err != nil {
		return err
	}
	rustFilePath := filepath.Join(sourceDirectory, "go_modules.rs")
	if err := os.WriteFile(rustFilePath, []byte(rustIndexFileTemplate), 0644); err != nil {
		return err
	}
	fmt.Fprintf(os.Stderr, "\nGenerated: %s\n", rustFilePath)
	return nil
}
