[package]
name = "lisette-lsp"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description.workspace = true
homepage.workspace = true
repository.workspace = true

[lib]
doctest = false

[dependencies]
syntax = { package = "lisette-syntax", version = "=0.12.1", path = "../syntax" }
semantics = { package = "lisette-semantics", version = "=0.12.1", path = "../semantics" }
passes = { package = "lisette-passes", version = "=0.12.1", path = "../passes" }
diagnostics = { package = "lisette-diagnostics", version = "=0.12.1", path = "../diagnostics" }
deps = { package = "lisette-deps", version = "=0.12.1", path = "../deps" }
format = { package = "lisette-format", version = "=0.12.1", path = "../format" }
rustc-hash.workspace = true
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
stdlib = { package = "lisette-stdlib", path = "../stdlib" }
tempfile = "3"

[lints]
workspace = true
