// Generated by Lisette bindgen. DO NOT EDIT.

pub(crate) const TYPEDEF_BUNDLE: &str = include_str!(concat!(env!("OUT_DIR"), "/go_typedefs.data"));

pub use crate::typedef_index::{
    get_go_stdlib_package_targets, get_go_stdlib_packages, get_go_stdlib_typedef,
};
