/// The Go package name a typedef header declares, present only when it differs
/// from the import path's last segment (e.g. `math/rand/v2` declares `rand`).
pub fn declared_package_name(typedef_source: &str) -> Option<&str> {
    for line in typedef_source.lines().take(HEADER_LINES) {
        let line = line.trim_start();
        if let Some(rest) = line.strip_prefix("// Package:") {
            let name = rest.trim();
            if !name.is_empty() {
                return Some(name);
            }
        }
        if !line.starts_with("//") && !line.is_empty() {
            break;
        }
    }
    None
}

/// Lines a typedef header can occupy, and so the most any reader needs.
pub const HEADER_LINES: usize = 10;

#[cfg(test)]
mod tests {
    use super::declared_package_name;

    #[test]
    fn directive_is_read_from_the_header() {
        let source = "// Generated by Lisette bindgen\n// Source: math/rand/v2 (Go stdlib)\n// Package: rand\n\npub fn Int() -> int\n";
        assert_eq!(declared_package_name(source), Some("rand"));
    }

    #[test]
    fn absent_directive_yields_none() {
        let source = "// Generated by Lisette bindgen\n\npub fn Clone(s: string) -> string\n";
        assert_eq!(declared_package_name(source), None);
    }

    #[test]
    fn declaration_ends_the_header() {
        let source = "pub fn Int() -> int\n// Package: rand\n";
        assert_eq!(declared_package_name(source), None);
    }
}
